name: UI Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  ui-regression-test-dev-webops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build Automation project for UI
        run: mvn install -DskipTests

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Connect to VPN
        run: sudo openvpn --config $GITHUB_WORKSPACE/webops-dev.ovpn --auth-user-pass $GITHUB_WORKSPACE/credentials.txt &

      - name: Login
        run: mvn test -Denvironment=dev -Dtenant="test8" -Dbrowser="chrome" -Dheadless="true" -Dcucumber.filter.tags="@login"

      - name: Upload UI artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ui-artifacts
          path: |
            UI/screenshots
            UI/target/cucumber-json/webops-automation-tests.json
            UI/target/surefire-report



